# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dung Duong
title: PhD Candidate in Computer Science
email: tridungduong16@gmail.com
website: https://tridungduong16.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  tridungduong16
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dung-duong-0a9107152
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dung Duong and I'm a PhD student in University of Technology Sydney.

  I am most skilled in: <mark>Python</mark> and <mark>Machine Learning</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FPT Telecom
        link: https://fpt.vn/en
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: Jan 2018 - Jan 2020
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Recommendation System
            * Preprocessing the films descriptions written in Vietnamese language by using many NLP techniques including cleaning punctuations, stopwords, html tags, tokenizing, part-of-speech
            * Building the topic modeling model for films description in order to convert text data to vector representation
            * Features engineering for the content-based algorithm
            * Keywords: recommendation system, topic model, natural language processing
            * Programming language: R, Python
                        
            Search Engine:
            * Building a search engine for retrieving films in fptplay.vn, which is based on Elastic Search framework
            along with the analysis of users’ log.
            * Utilising the statistics including the number of people searching and viewing a film and the frequency of
            keywords appearance from users’ to enhance the performance and precision of the returned results
            * Using the analyzer to tokenize and analyze the Vietnamese language
            * Keywords: information retrieval system, Elastic Search, NLP, features engineering
            
            Commercial Detection
            * Research the Shazam’s approach for audio recognition.
            * Cut advertisements from TV channel videos, convert them into the hash value and insert into database.
            * Detect advertisements in a video by searching them in database.
            Energy Consumption Prediction
            * Analyze and feature engineering time-series data
            * Build LSTM model for predicting energy consumption in a Vietnamese region
            * Keywords: LSTM model, time-series data, prediction model

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Technology Sydney (UTS)
        caption: 2020 - Present
        sub_title: PhD Computer Science
        quote: >
          UTS is number one young university in Australia. 
        description: | # this will include new lines to allow paragraphs
          I do PhD in computer science in UTS. 

  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Xu, Guandong, et al. A New Perspective for Interpretable Machine Learning.
        link: https://arxiv.org/abs/2006.16789
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Recent years have witnessed the rapid growth of machine learning in a wide range of fields such as image recognition, text classification, credit scoring prediction, recommendation system, etc. In spite of their great performance in different sectors, researchers still concern about the mechanism under any machine learning (ML) techniques that are inherently black-box and becoming more complex to achieve higher accuracy. Therefore, interpreting machine learning model is currently a mainstream topic in the research community. However, the traditional interpretable machine learning focuses on the association instead of the causality. This paper provides an overview of causal analysis with the fundamental background and key concepts, and then summarizes most recent causal approaches for interpretable machine learning. The evaluation techniques for assessing method quality, and open problems in causal interpretability are also discussed in this paper.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      #Look at this cool image  
      #![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
